databases:
  - name: sample_DB # 編集 (Renderで作成したデータベース名)
    databaseName: sample_db_n6x3 # 編集 (Renderで作成したデータベースのところにあるInfo>Connections>Database)
    user: sample # 編集 (Renderで作成したデータベースのところにあるInfo>Connections>Username)
    region: singapore

services:
  - type: web
    name: sample_app # 編集 (Renderで作成したWeb Serviceの名前)
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sample_DB # 編集 (Renderで作成したデータベース名)
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false